importScripts(
  "/background/config.js",
  "/background/localStorage.js",
  "/background/api.js",
  "/background/auth.js",
  "/background/jobcodesAndTimesheets.js",
  "/background/badge.js",
  "/background/audioPlayback.js",
  "/background/pollingScript.js"
);
